require('dotenv').config();const express=require('express'),mongoose=require('mongoose'),cors=require('cors'),path=require('path'),fs=require('fs'),multer=require('multer'),jwt=require('jsonwebtoken');
const app=express(),PORT=process.env.PORT||5000,uploadDir=path.join(__dirname,'uploads');if(!fs.existsSync(uploadDir))fs.mkdirSync(uploadDir,{recursive:true});
app.use(cors());app.use(express.json());app.use(express.urlencoded({extended:true}));app.use('/uploads',express.static(uploadDir));app.use('/admin',express.static(path.join(__dirname,'admin')));app.use(express.static(path.join(__dirname,'public')));
mongoose.connect(process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/faisal_cosmetics').then(()=>console.log('MongoDB connected')).catch(e=>console.error(e.message));
const Product=mongoose.model('Product',new mongoose.Schema({name:{type:String,required:true},category:{type:String,required:true},subcategory:String,brand:String,price:Number,salePrice:Number,stock:Number,image:String,description:String,featured:Boolean,topProduct:Boolean,createdAt:{type:Date,default:Date.now}}));
const Order=mongoose.model('Order',new mongoose.Schema({customer:{name:String,phone:String,address:String},items:[{productId:String,name:String,price:Number,qty:Number}],total:Number,status:{type:String,default:'Pending'},createdAt:{type:Date,default:Date.now}}));
const storage=multer.diskStorage({destination:uploadDir,filename:(r,f,cb)=>cb(null,Date.now()+'-'+Math.random().toString(36).slice(2)+path.extname(f.originalname).toLowerCase())});const upload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(r,f,cb)=>cb(null,/^image\//.test(f.mimetype))});
function auth(req,res,next){try{req.admin=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),process.env.JWT_SECRET||'dev-secret');next()}catch(e){res.status(401).json({message:'Unauthorized'})}}
app.post('/api/auth/login',(req,res)=>{if(req.body.username!==(process.env.ADMIN_USERNAME||'admin')||req.body.password!==(process.env.ADMIN_PASSWORD||'admin123'))return res.status(401).json({message:'Invalid login'});res.json({token:jwt.sign({username:req.body.username},process.env.JWT_SECRET||'dev-secret',{expiresIn:'7d'})})});
app.get('/api/products',async(req,res)=>{try{let q={};if(req.query.category)q.category=req.query.category;if(req.query.search)q.$or=['name','brand','category'].map(k=>({[k]:{$regex:req.query.search,$options:'i'}}));if(req.query.featured==='true')q.featured=true;if(req.query.top==='true')q.topProduct=true;res.json(await Product.find(q).sort({createdAt:-1}))}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/products/:id',async(req,res)=>{try{res.json(await Product.findById(req.params.id))}catch(e){res.status(404).json({message:'Not found'})}});
app.post('/api/products',auth,upload.single('image'),async(req,res)=>{try{res.status(201).json(await Product.create({...req.body,price:+req.body.price,salePrice:+(req.body.salePrice||0),stock:+(req.body.stock||0),featured:req.body.featured==='true',topProduct:req.body.topProduct==='true',image:req.file?'/uploads/'+req.file.filename:req.body.image||''}))}catch(e){res.status(400).json({message:e.message})}});
app.put('/api/products/:id',auth,upload.single('image'),async(req,res)=>{try{let d={...req.body,price:+req.body.price,salePrice:+(req.body.salePrice||0),stock:+(req.body.stock||0),featured:req.body.featured==='true',topProduct:req.body.topProduct==='true'};if(req.file)d.image='/uploads/'+req.file.filename;res.json(await Product.findByIdAndUpdate(req.params.id,d,{new:true}))}catch(e){res.status(400).json({message:e.message})}});
app.delete('/api/products/:id',auth,async(req,res)=>{await Product.findByIdAndDelete(req.params.id);res.json({message:'Deleted'})});
app.post('/api/orders',async(req,res)=>{try{let{customer,items}=req.body,total=0,final=[];if(!customer?.name||!customer?.phone||!customer?.address||!items?.length)return res.status(400).json({message:'Complete customer details required'});for(const i of items){let p=await Product.findById(i.productId),qty=Math.max(1,+i.qty);if(!p||p.stock<qty)return res.status(400).json({message:'Insufficient stock'});let price=p.salePrice>0?p.salePrice:p.price;total+=price*qty;final.push({productId:p._id.toString(),name:p.name,price,qty})}for(const i of final)await Product.findByIdAndUpdate(i.productId,{$inc:{stock:-i.qty}});res.status(201).json(await Order.create({customer,items:final,total}))}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/orders',auth,async(req,res)=>res.json(await Order.find().sort({createdAt:-1})));app.patch('/api/orders/:id/status',auth,async(req,res)=>res.json(await Order.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true})));
app.get('/api/dashboard',auth,async(req,res)=>{let[products,orders,customers,agg]=await Promise.all([Product.countDocuments(),Order.countDocuments(),Order.distinct('customer.phone'),Order.aggregate([{$match:{status:{$ne:'Cancelled'}}},{$group:{_id:null,total:{$sum:'$total'}}}])]);res.json({products,orders,customers:customers.length,sales:agg[0]?.total||0})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log('Server: http://localhost:'+PORT));
